# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2643c6cd114dab497b2e1764c69a9df"
<<<<<<< HEAD
application_url = "https://kenny-phil-characterized-functioning.trycloudflare.com"
=======
application_url = "https://rooms-any-accessory-msgstr.trycloudflare.com"
>>>>>>> 410db93e735bc68501a4d6ed3984907bed74a6bd
embedded = true
name = "FAQ"
handle = "faq-39"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://kenny-phil-characterized-functioning.trycloudflare.com/auth/callback",
  "https://kenny-phil-characterized-functioning.trycloudflare.com/auth/shopify/callback",
  "https://kenny-phil-characterized-functioning.trycloudflare.com/api/auth/callback"
=======
  "https://rooms-any-accessory-msgstr.trycloudflare.com/auth/callback",
  "https://rooms-any-accessory-msgstr.trycloudflare.com/auth/shopify/callback",
  "https://rooms-any-accessory-msgstr.trycloudflare.com/api/auth/callback"
>>>>>>> 410db93e735bc68501a4d6ed3984907bed74a6bd
]

[pos]
embedded = false

[build]
dev_store_url = "test-learning-app.myshopify.com"
automatically_update_urls_on_dev = true
