# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2643c6cd114dab497b2e1764c69a9df"
<<<<<<< HEAD
application_url = "https://replies-international-animation-martha.trycloudflare.com"
=======
application_url = "https://static-type-balloon-isa.trycloudflare.com"
>>>>>>> bd37ef1eebb7f9cd1ba37557f11c676f60d65bb0
embedded = true
name = "FAQ"
handle = "faq-39"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://replies-international-animation-martha.trycloudflare.com/auth/callback",
  "https://replies-international-animation-martha.trycloudflare.com/auth/shopify/callback",
  "https://replies-international-animation-martha.trycloudflare.com/api/auth/callback"
=======
  "https://static-type-balloon-isa.trycloudflare.com/auth/callback",
  "https://static-type-balloon-isa.trycloudflare.com/auth/shopify/callback",
  "https://static-type-balloon-isa.trycloudflare.com/api/auth/callback"
>>>>>>> bd37ef1eebb7f9cd1ba37557f11c676f60d65bb0
]

[pos]
embedded = false

[build]
dev_store_url = "test-learning-app.myshopify.com"
automatically_update_urls_on_dev = true
